version: '3.9'

x-mayan-container:
  &mayan-container
  depends_on:
    - postgresql
    - redis
    # Enable to use RabbitMQ
    #- rabbitmq
  env_file: env_file
  environment:
    # Enable to use RabbitMQ
    # MAYAN_CELERY_BROKER_URL: amqp://${MAYAN_RABBITMQ_USER:-mayan}:${MAYAN_RABBITMQ_PASSWORD:-mayanrabbitpass}@rabbitmq:5672/${MAYAN_RABBITMQ_VHOST:-mayan}
    # To use RabbitMQ as broker, disable Redis as broker
    PYTHONDONTWRITEBYTECODE: 1
    MAYAN_CELERY_BROKER_URL: redis://:mayanredispassword@172.17.0.1:6379/0
    MAYAN_CELERY_RESULT_BACKEND: redis://:mayanredispassword@172.17.0.1:6379/1
    MAYAN_DATABASES: "{'default':{'ENGINE':'django.db.backends.postgresql','NAME':'mayan','PASSWORD':'mayanuserpass','USER':'mayan','HOST':'172.17.0.1'}}"
    MAYAN_LOCK_MANAGER_BACKEND: mayan.apps.lock_manager.backends.redis_lock.RedisLock
    MAYAN_LOCK_MANAGER_BACKEND_ARGUMENTS: "{'redis_url':'redis://:mayanredispassword@172.17.0.1:6379/2'}"
    # Replace with the line below when using RabbitMQ
    # MAYAN_DOCKER_WAIT: "${MAYAN_DATABASE_HOST:-postgresql}:5432 redis:6379 rabbitmq:5672"
  image: mayanedms/mayanedms:4.0.7
  networks:
    - bridge
  restart: unless-stopped
  volumes:
    - /docker-volumes/mayan-edms/media:/var/lib/mayan
    # Optional volumes to access external data like staging or watch folders
    # - /opt/staging_files:/staging_files
    # - /opt/watch_folder:/watch_folder

networks:
  bridge:
    driver: bridge

services:
  app:
    <<: *mayan-container
    ports:
      - "80:8000"

  postgresql:
    command:
      - "postgres"
      - "-c"
      - "checkpoint_completion_target=0.6"
      - "-c"
      - "default_statistics_target=200"
      - "-c"
      - "maintenance_work_mem=128MB"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "work_mem=8MB"
    environment:
      POSTGRES_DB: mayan
      POSTGRES_PASSWORD: mayanuserpass
      POSTGRES_USER: mayan
    image: postgres:10.15-alpine
    networks:
      - bridge
    # Disable to allow external access to the database.    
    ports:
     - "5432:5432"
    restart: unless-stopped
    volumes:
      - /docker-volumes/mayan-edms/postgres:/var/lib/postgresql/data

  redis:
    command:
      - redis-server
      - --appendonly
      - "no"
      - --databases
      - "3"
      - --maxmemory
      - "100mb"
      - --maxclients
      - "500"
      - --maxmemory-policy
      - "allkeys-lru"
      - --save
      - ""
      - --tcp-backlog
      - "256"
      - --requirepass
      - "${MAYAN_REDIS_PASSWORD:-mayanredispassword}"
    image: redis:${MAYAN_DOCKER_REDIS_TAG:-6.0-alpine}
    networks:
      - bridge
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - /docker-volumes/mayan-edms/redis:/data